### ISSUE TITLE
“”

### ISSUE THREAD

**Issue by xuliang0909** [TriHuynh00/AC3R-Demo#3]
Hello sir,
A few months ago I asked you how to run AC3R related issues, thank you very much for your help. Recently, I ran into a problem when running AC3R. I tried to load a lot of cases, but they all failed because of "noCrash". Why? Below I will attach my log file:
![image](https://user-images.githubusercontent.com/45282116/79039242-80c6f700-7c12-11ea-8dcd-2fbaf44639f8.png)
[log0.txt](https://github.com/SoftLegend/AC3R-Demo/files/4464275/log0.txt)
[log4.txt](https://github.com/SoftLegend/AC3R-Demo/files/4464276/log4.txt)

In addition, during this global outbreak, I wish you and your family peace and security!

**Comment by alessiogambi** [comment]
Hi,
there might be many reasons why the simulation did not result in the expected crash. Have you checked if the beamng scenario looks fine? Can you provide a bit more details about the police report that you used (maybe the ID and or the URL where it can be downloaded)

**Comment by xuliang0909** [comment]
Thank you, sir. I solved the problem by modifying the basic file. Now I can run the AC3R crash report.
![QQ截图20200415014822](https://user-images.githubusercontent.com/45282116/79309729-5b492e80-7f2d-11ea-9d3c-e43070aa9163.png)
